export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_PAGE = 'GET_PAGE';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';
export const GET_PAGE_FAIL = 'GET_PAGE_FAIL';


export const CREATE_PAGE = 'CREATE_PAGE';
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS';
export const CREATE_PAGE_FAIL = 'CREATE_PAGE_FAIL';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL';

export const CREATE_NEWS_ARTICLE = 'CREATE_NEWS_ARTICLE';
export const CREATE_NEWS_ARTICLE_SUCCESS = 'CREATE_NEWS_ARTICLE_SUCCESS';
export const CREATE_NEWS_ARTICLE_FAIL = 'CREATE_NEWS_ARTICLE_FAIL';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';

export const GET_LINK_PREVIEW = 'GET_LINK_PREVIEW';
export const GET_LINK_PREVIEW_SUCCESS = 'GET_LINK_PREVIEW_SUCCESS';
export const GET_LINK_PREVIEW_FAIL = 'GET_LINK_PREVIEW_FAIL';