// Space Types
export const CREATE_SPACE = 'CREATE_SPACE';
export const CREATE_SPACE_SUCCESS = 'CREATE_SPACE_SUCCESS';
export const CREATE_SPACE_FAIL = 'CREATE_SPACE_FAIL';
export const GET_SPACE = 'GET_SPACE';
export const GET_SPACE_SUCCESS = 'GET_SPACE_SUCCESS';
export const GET_SPACE_FAIL = 'GET_SPACE_FAIL';